{% set name = "checksumdir" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/checksumdir-{{ version }}.tar.gz
  sha256: 11693641be49defbfdfb13612a7fd70ce1acd5401db74105f8c486fd72046540

build:
  entry_points:
    - checksumdir = checksumdir.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - checksumdir
  commands:
    - pip check
    - checksumdir --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/cakepietoast/checksumdir
  summary: Compute a single hash of the file contents of a directory.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bmcconeghy
    - asford
